#!/usr/bin/env python

# munin plugin to gather resident-size for
# all specified user ids. Specify ids below
# in a comma-separated list (no spaces).

users = 'plone,zope'

import sys
import re
import subprocess

ps_command = 'ps -o rss= -o command= -U %s' % users
command_re = re.compile(r'\s(\S+)(\.conf| fg)')
pid_split = re.compile(r'^(\d+) +(.+)$')

config = len(sys.argv) > 1 and sys.argv[1].lower() == 'config'
if config:
    print "graph_title %s process memory" % users
    print "graph_vlabel MB"
    print "graph_category plone"
    print "graph_scale no"

ps_out = subprocess.Popen(
    ps_command.split(),
    stdout=subprocess.PIPE
    ).stdout.read()

for line in ps_out.split('\n'):
    # print line
    match = pid_split.match(line)
    if match:
        res, command = match.groups()
        # print res, command
        cmatch = command_re.search(command)
        if cmatch:
            cstr = cmatch.groups()[0].replace('/', '_'
                ).replace('_parts', ''
                ).replace('_etc', ''
                ).replace('_zope', ''
                ).replace('zeo_', ''
                ).replace('zeocluster_', ''
                ).strip('_'
                ).replace('var_db_', ''
                ).replace('opt_', ''
                ).replace('.', ''
                ).replace('_', ''
                ).lower()
            if config:
                print "%s.label %s" % (cstr, cstr)
            else:
                print "%s.value %d" % (cstr, int(res) / 1024)
